function g = testtournament()

  individuals = [ ...
    struct('fitness', 10), ...
    struct('fitness', 9), ...
    struct('fitness', 5), ...
    struct('fitness', 4), ...
    struct('fitness', 1), ...
    struct('fitness', 2)
  ];
  
  g = tournament(individuals, 9, 0.75);
end