function g = testroulette()

  individuals = [ ...
    struct('fitness', 1), ...
    struct('fitness', 3), ...
    struct('fitness', 5), ...
    struct('fitness', 10)
  ];
  
  g = roulette(individuals, 10);
end