% Run the learn algorithm.

DIMS = 2;
NEURONS = [5 3 1];
W = get_random_w([DIMS NEURONS], 0.8);
g = @tanh;
gp = @(x)(sech(x).^2);


for i = 1:4
  
  print_matrix(W);
  params = struct(...
    'eta', 0.3, ...
    'alpha', 0.3, ...
    'noise_factor', 0.0001, ...
    'hard_limit', 1500, ...
    'adaptative_increment', 0.05 * i, ...
    'adaptative_decrement', 0.001, ...
    'adaptative_steps', 3, ...
    'debug', true ...
  );
  data = execute_learn_algorithm(W, NEURONS, g, gp, DIMS, params);
  save(['increment_' num2str(i) '_data_result.m'], ['data']);
end
