% Run the learn algorithm.

DIMS = 2;
NEURONS = [8 4 1];
W = get_random_w([DIMS NEURONS], 0.3);
g = @tanh;
gp = @(x)(sech(x).^2);


for i = 1:5
  
print_matrix(W);
  params = struct(...
    'eta', 0.5, ...
    'alpha', -0.1 + i * 0.2, ...
    'noise_factor', 0.0001, ...
    'hard_limit', 1500, ...
    'adaptative_increment', 0.1, ...
    'adaptative_decrement', 0.001, ...
    'debug', true ...
  );
  data = execute_learn_algorithm(W, NEURONS, g, gp, DIMS, params);
  save(['alpha_' num2str(-0.1 + 0.2 * i) '_data_result.m'], ['data']);
end
