function algo = generate_replace_algorithm(selection_method)
  algo = @(status, params)( ...
    struct(...
     'N', status.N, ...
     'g', status.g + 1, ...
     'p', selection_method(...
         status.p, ...
        params.selection_algorithm, ...
        params.selection_algorithm_2, ...
        params.cross_algorithm, ...
        params.mutate_algorithm, params ...
     ) ...
    ) ...
  );
end