function data = main()

  load('initial_population.mat');

  s = RandStream('mcg16807','Seed',0);
  RandStream.setGlobalStream(s);

  selection_algorithm = @elite;
  cross_algorithm = @crossover;
  mutate_algorithm = @single_mutate;
  
  params = struct(...
    'N', 20, ...
    'replace_algorithm', generate_replace_algorithm(@select_1), ...
    'selection_algorithm', @elite, ...
    'selection_algorithm_2', @elite, ...
    'cross_algorithm', @crossover, ...
    'mutate_algorithm', @(x)(single_mutate(x.i, 0.95, (rand()-0.5))), ...
    'backpropagate_probablility', 0.1, ...
    'done', generation_limit(10), ...
    'use_first_gen', true, ...
    'first_generation', m.p ...
  );

  data = run_genetic_algorithm(params);
  
end