function g = testrank()

  individuals = [ ...
    struct('fitness', 10), ...
    struct('fitness', 14), ...
    struct('fitness', 1000), ...
    struct('fitness', 2)
  ];
  
  g = rank(individuals, 9);
end