function g = testelite()

  individuals = [ ...
    struct('fitness', 200), ...
    struct('fitness', 10), ...
    struct('fitness', 14), ...
    struct('fitness', 1000), ...
    struct('fitness', 1), ...
    struct('fitness', 2000), ...
    struct('fitness', 2)
  ];
  
  g = elite(individuals, 3);
end